### ISSUE TITLE
Tests using base64 profile encodings fail on Mac

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#61]
Tests using base64 profile encodings fail on Mac.

**Comment by ofrobots** [comment]
Example failure:

```
❯ npm run compile && npx mocha --require source-map-support/register out/test/test-profiler.js -g 'should return expected profile when profile type is WALL'

> @google-cloud/profiler@0.1.5 compile /Users/ofrobots/src/stackdriver/profiler
> tsc -p .



  Profiler
    profile
      1) should return expected profile when profile type is WALL.


  0 passing (51ms)
  1 failing

  1) Profiler
       profile
         should return expected profile when profile type is WALL.:

      AssertionError [ERR_ASSERTION]: 'H4sIAAAAAAAAE0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6Q deepEqual 'H4sIAAAAAAAAA0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6Q
      + expected - actual

      -H4sIAAAAAAAAE0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6QkVVwlKECB5ihaxUMZii2Z2mFP84KXCQq0KEQpUXRRYlZGjOe2vzWj4babfDAsuLYx69bZoRsb2/nLaNLr5G1wnTdYt4Prg/ln9S+r96vD/f18bI/LM6dZfAGLaAVw3AAAAA==
      +H4sIAAAAAAAAA0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6QkVVwlKECB5ihaxUMZii2Z2mFP84KXCQq0KEQpUXRRYlZGjOe2vzWj4babfDAsuLYx69bZoRsb2/nLaNLr5G1wnTdYt4Prg/ln9S+r96vD/f18bI/LM6dZfAGLaAVw3AAAAA==

      at Object.<anonymous> (ts/test/test-profiler.ts:97:17)
      at step (out/test/test-profiler.js:47:23)
      at Object.next (out/test/test-profiler.js:28:53)
      at fulfilled (out/test/test-profiler.js:19:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


```

**Comment by nolanmar511** [comment]
When I decode the base64 encode profiles from linux and mac, they are different. When I inspect these using gqui, the output is identical.

I think there's just a difference in exactly how the files are compressed on mac and on linux, based on the following commands:

```
> echo 'H4sIAAAAAAAAA0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6QkVVwlKECB5ihaxUMZii2Z2mFP84KXCQq0KEQpUXRRYlZGjOe2vzWj4babfDAsuLYx69bZoRsb2/nLaNLr5G1wnTdYt4Prg/ln9S+r96vD/f18bI/LM6dZfAGLaAVw3AAAAA==' | base64 -d > linux.pb.gz
> echo 'H4sIAAAAAAAAE0XPMQrCMBQGYPOSNGkQGrrYsRRc3JpTODo7KbFCwKalTXeP4g1cPYKjx+gxfCmI28f//vfgKSaJBsUk1SxPFQDJKZlFLhWBnNLXJoYUCZ8sksEyr6QkVVwlKECB5ihaxUMZii2Z2mFP84KXCQq0KEQpUXRRYlZGjOe2vzWj4babfDAsuLYx69bZoRsb2/nLaNLr5G1wnTdYt4Prg/ln9S+r96vD/f18bI/LM6dZfAGLaAVw3AAAAA==' | base64 -d > mac.pb.gz
> diff linux.pb.gz mac.pb.gz 
Binary files linux.pb.gz and mac.pb.gz differ
> gunzip linux.pb.gz 
> gunzip mac.pb.gz 
> diff linux.pb mac.pb 
(no output)
```

I'm going to close this, because I have adjusted the tests so they no longer depend on the base64 encoded compressed strings (so this issue does not prevent the test from passing on mac), and I don't think there's much else to be done with this, but feel free to reopen
