### ISSUE TITLE
Add back source-map-support for better stack traces 

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#68]
When running tests in #56, tests passed prior to merging in #60 and failed after, with the following stack trace:

```
/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/util.js:344
  var cmp = mappingA.generatedLine - mappingB.generatedLine;
                                              ^

TypeError: Cannot read property 'generatedLine' of undefined
    at compareByGeneratedPositionsDeflated (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/util.js:344:47)
    at doQuickSort (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/quick-sort.js:88:11)
    at exports.quickSort (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/quick-sort.js:113:3)
    at BasicSourceMapConsumer.SourceMapConsumer_parseMappings [as _parseMappings] (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/source-map-consumer.js:564:5)
    at BasicSourceMapConsumer.get [as _generatedMappings] (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/source-map-consumer.js:70:12)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map/lib/source-map-consumer.js:655:12)
    at mapSourcePosition (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map-support/source-map-support.js:199:42)
    at wrapCallSite (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map-support/source-map-support.js:343:20)
    at /usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map-support/source-map-support.js:378:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map-support/source-map-support.js:377:24)
    at /usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/reporters/base.js:184:21
    at Array.forEach (<anonymous>)
    at Function.exports.list (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/reporters/base.js:167:12)
    at Spec.Base.epilogue (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/reporters/base.js:344:10)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/runner.js:829:12
    at done (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/runner.js:666:7)
    at Runner.next [as nextSuite] (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/runner.js:633:16)
    at Runner.uncaught (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/runner.js:754:17)
    at process.uncaught (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/mocha/lib/runner.js:821:10)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at processEmit (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/usr/local/google/home/nolanmar/cloud-profiler-nodejs/node_modules/source-map-support/source-map-support.js:439:21)
    at process._fatalException (bootstrap_node.js:374:26)
```

#56 will undo changes from #60.

**Comment by nolanmar511** [comment]
Still fails with the same error when added.
