### ISSUE TITLE
Sporadic heap profiler segfault with Node.js 6

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#90]
Using node version 6.12.0, there are sporadic segmentation faults.

Running with gdb, the backtrace looked like this:

```
#0  0x0000000000c7b5a7 in v8::internal::InnerPointerToCodeCache::GetCacheEntry(unsigned char*) ()
#1  0x0000000000c7d0ef in v8::internal::StackFrame::GetCallerState(v8::internal::StackFrame::State*) const ()
#2  0x0000000000c7941d in v8::internal::StackFrameIterator::Advance() ()
#3  0x0000000000c79a28 in v8::internal::StackTraceFrameIterator::Advance() ()
#4  0x0000000000e439c4 in v8::internal::SamplingHeapProfiler::AddStack() ()
#5  0x0000000000e44996 in v8::internal::SamplingHeapProfiler::SampleObject(unsigned char*, unsigned long) ()
#6  0x0000000000cf277e in v8::internal::FreeList::Allocate(int) ()
#7  0x0000000000c5e350 in v8::internal::PagedSpace::AllocateRawUnaligned(int, v8::internal::PagedSpace::UpdateSkipList) ()
#8  0x0000000000c94d87 in v8::internal::Heap::AllocateRaw(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) ()
#9  0x0000000000ca5d20 in v8::internal::Heap::AllocateCode(int, bool) ()
#10 0x0000000000c67068 in v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) ()
#11 0x0000000000a28bc7 in v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::CompilationInfo*) ()
#12 0x0000000000c7f78d in v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) ()
#13 0x0000000000b4e6de in v8::internal::(anonymous namespace)::GenerateBaselineCode(v8::internal::CompilationInfo*) ()
#14 0x0000000000b50ac0 in v8::internal::(anonymous namespace)::GetUnoptimizedCodeCommon(v8::internal::CompilationInfo*) ()
#15 0x0000000000b58186 in v8::internal::(anonymous namespace)::GetLazyCode(v8::internal::Handle<v8::internal::JSFunction>) ()
#16 0x0000000000b5840c in v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) ()
#17 0x0000000000e8cf66 in v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) ()
#18 0x00000f2b0c5092a7 in ?? ()
#19 0x00000f2b0c5091e1 in ?? ()
#20 0x00007fffffffcea0 in ?? ()
#21 0x0000000300000000 in ?? ()
#22 0x00007fffffffcef8 in ?? ()
#23 0x00000f2b0c530b18 in ?? ()
#24 0x00001e6d6a30fed1 in ?? ()
#25 0x00001bf16d304381 in ?? ()
#26 0x00001e6d6a30fed1 in ?? ()
#27 0x0000000200000000 in ?? ()
#28 0x00000f2b0c530a81 in ?? ()
#29 0x0000000c00000000 in ?? ()
#30 0x00007fffffffcf98 in ?? ()
#31 0x00000f2b0d3ca1ce in ?? ()
#32 0x00001e6d6a310a49 in ?? ()
#33 0x00001e6d6a311019 in ?? ()
#34 0x00001bf16d304381 in ?? ()
#35 0x00001e6d6a30fed1 in ?? ()
#36 0x00001e6d6a310909 in ?? ()
#37 0x00001bf16d304381 in ?? ()
#38 0x00001bf16d304381 in ?? ()
#39 0x00001bf16d304381 in ?? ()
#40 0x00001e6d6a3121b1 in ?? ()
#41 0x00001e6d6a311051 in ?? ()
#42 0x00001e6d6a30f4e1 in ?? ()
#43 0x00001e6d6a311019 in ?? ()
#44 0x00001e6d6a310e49 in ?? ()
#45 0x00001e6d6a310b91 in ?? ()
#46 0x00001e6d6a310ad9 in ?? ()
#47 0x00001e6d6a310a49 in ?? ()
#48 0x00000cb0b2b553e1 in ?? ()
#49 0x00001e6d6a3108a1 in ?? ()
#50 0x00007fffffffd010 in ?? ()
#51 0x00000f2b0d3ebdca in ?? ()
#52 0x00001e6d6a30ff41 in ?? ()
#53 0x00001e6d6a30fed1 in ?? ()
#54 0x00001e6d6a30b4e9 in ?? ()
#55 0x00001e6d6a3105c1 in ?? ()
#56 0x00001bf16d304381 in ?? ()
#57 0x00000cb0b2b553e1 in ?? ()
#58 0x00001e6d6a3105c1 in ?? ()
#59 0x00001e6d6a3104a9 in ?? ()
#60 0x00001e6d6a310211 in ?? ()
#61 0x00001e6d6a30ff41 in ?? ()
#62 0x00001e6d6a30fed1 in ?? ()
#63 0x00000cb0b2b5eeb1 in ?? ()
#64 0x00001e6d6a30fe99 in ?? ()
#65 0x00007fffffffd060 in ?? ()
#66 0x00000f2b0d372dd1 in ?? ()
#67 0x000003e800000000 in ?? ()
#68 0x00001e6d6a30b459 in ?? ()
#69 0x00000cb0b2bcd6a1 in ?? ()
```

**Comment by aalexand** [comment]
@ofrobots Assigning to you to ping the bug with the exact version of released Node.js when it's available. Then reassign to @nolanmar to verify and close.

**Comment by ofrobots** [comment]
This should be in today's RC as per [this comment.](https://github.com/nodejs/node/pull/17639#issuecomment-352858583)

**Comment by nolanmar511** [comment]
Node 6.12.3 was released today. I have been running multiple copies a simple test application for the past 3 or 4 hours and have not seen any segmentation faults. 
I'll leave the applications running overnight and re-open if there are any segmentation faults.
